"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.query_aggregate_result import QueryAggregateResult
from openapi_client.model.query_collection_response_pipeline import QueryCollectionResponsePipeline
from openapi_client.model.query_result import QueryResult
globals()['QueryAggregateResult'] = QueryAggregateResult
globals()['QueryCollectionResponsePipeline'] = QueryCollectionResponsePipeline
globals()['QueryResult'] = QueryResult
from openapi_client.model.query_collection_response import QueryCollectionResponse


class TestQueryCollectionResponse(unittest.TestCase):
    """QueryCollectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryCollectionResponse(self):
        """Test QueryCollectionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryCollectionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
