"""
    Search.io API

    Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import sajari_client
from sajari_client.api.redirects_api import RedirectsApi  # noqa: E501


class TestRedirectsApi(unittest.TestCase):
    """RedirectsApi unit test stubs"""

    def setUp(self):
        self.api = RedirectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_redirect(self):
        """Test case for create_redirect

        Create redirect  # noqa: E501
        """
        pass

    def test_delete_redirect(self):
        """Test case for delete_redirect

        Delete redirect  # noqa: E501
        """
        pass

    def test_get_redirect(self):
        """Test case for get_redirect

        Get redirect  # noqa: E501
        """
        pass

    def test_list_redirects(self):
        """Test case for list_redirects

        List redirects  # noqa: E501
        """
        pass

    def test_update_redirect(self):
        """Test case for update_redirect

        Update redirect  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
