"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.pipeline_step_param_binding import PipelineStepParamBinding
globals()['PipelineStepParamBinding'] = PipelineStepParamBinding
from sajari_client.model.pipeline_step import PipelineStep


class TestPipelineStep(unittest.TestCase):
    """PipelineStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPipelineStep(self):
        """Test PipelineStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PipelineStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
