"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.record_key import RecordKey
globals()['RecordKey'] = RecordKey
from openapi_client.model.upsert_record_response import UpsertRecordResponse


class TestUpsertRecordResponse(unittest.TestCase):
    """UpsertRecordResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpsertRecordResponse(self):
        """Test UpsertRecordResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpsertRecordResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
