"""
    Search.io API

    Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.status import Status
globals()['Status'] = Status
from sajari_client.model.batch_update_records_response_error import BatchUpdateRecordsResponseError


class TestBatchUpdateRecordsResponseError(unittest.TestCase):
    """BatchUpdateRecordsResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchUpdateRecordsResponseError(self):
        """Test BatchUpdateRecordsResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BatchUpdateRecordsResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
