"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import sajari_client
from sajari_client.api.collections_api import CollectionsApi  # noqa: E501


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_collection(self):
        """Test case for create_collection

        Create collection  # noqa: E501
        """
        pass

    def test_delete_collection(self):
        """Test case for delete_collection

        Delete collection  # noqa: E501
        """
        pass

    def test_get_collection(self):
        """Test case for get_collection

        Get collection  # noqa: E501
        """
        pass

    def test_list_collections(self):
        """Test case for list_collections

        List collections  # noqa: E501
        """
        pass

    def test_query_collection(self):
        """Test case for query_collection

        Query collection  # noqa: E501
        """
        pass

    def test_update_collection(self):
        """Test case for update_collection

        Update collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
