"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.generate_pipelines_request import GeneratePipelinesRequest


class TestGeneratePipelinesRequest(unittest.TestCase):
    """GeneratePipelinesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneratePipelinesRequest(self):
        """Test GeneratePipelinesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneratePipelinesRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
