"""
    Search.io API

    Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.promotion import Promotion
globals()['Promotion'] = Promotion
from sajari_client.model.list_promotions_response import ListPromotionsResponse


class TestListPromotionsResponse(unittest.TestCase):
    """ListPromotionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPromotionsResponse(self):
        """Test ListPromotionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPromotionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
