"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.query_collection_request_pipeline import QueryCollectionRequestPipeline
from openapi_client.model.query_collection_request_tracking import QueryCollectionRequestTracking
globals()['QueryCollectionRequestPipeline'] = QueryCollectionRequestPipeline
globals()['QueryCollectionRequestTracking'] = QueryCollectionRequestTracking
from openapi_client.model.query_collection_request import QueryCollectionRequest


class TestQueryCollectionRequest(unittest.TestCase):
    """QueryCollectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryCollectionRequest(self):
        """Test QueryCollectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryCollectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
