"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.collection import Collection

globals()["Collection"] = Collection
from sajari_client.model.list_collections_response import ListCollectionsResponse


class TestListCollectionsResponse(unittest.TestCase):
    """ListCollectionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCollectionsResponse(self):
        """Test ListCollectionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCollectionsResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
