"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import sajari_client
from sajari_client.api.pipelines_api import PipelinesApi  # noqa: E501


class TestPipelinesApi(unittest.TestCase):
    """PipelinesApi unit test stubs"""

    def setUp(self):
        self.api = PipelinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pipeline(self):
        """Test case for create_pipeline

        Create pipeline  # noqa: E501
        """
        pass

    def test_generate_pipelines(self):
        """Test case for generate_pipelines

        Generate pipelines  # noqa: E501
        """
        pass

    def test_get_default_pipeline(self):
        """Test case for get_default_pipeline

        Get default pipeline  # noqa: E501
        """
        pass

    def test_get_default_version(self):
        """Test case for get_default_version

        Get default pipeline version  # noqa: E501
        """
        pass

    def test_get_pipeline(self):
        """Test case for get_pipeline

        Get pipeline  # noqa: E501
        """
        pass

    def test_list_pipelines(self):
        """Test case for list_pipelines

        List pipelines  # noqa: E501
        """
        pass

    def test_set_default_pipeline(self):
        """Test case for set_default_pipeline

        Set default pipeline  # noqa: E501
        """
        pass

    def test_set_default_version(self):
        """Test case for set_default_version

        Set default pipeline version  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
