"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.status import Status
globals()['Status'] = Status
from sajari_client.model.batch_create_schema_fields_response_error import BatchCreateSchemaFieldsResponseError


class TestBatchCreateSchemaFieldsResponseError(unittest.TestCase):
    """BatchCreateSchemaFieldsResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchCreateSchemaFieldsResponseError(self):
        """Test BatchCreateSchemaFieldsResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BatchCreateSchemaFieldsResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
