"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.percentile_data_point import PercentileDataPoint


class TestPercentileDataPoint(unittest.TestCase):
    """PercentileDataPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPercentileDataPoint(self):
        """Test PercentileDataPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PercentileDataPoint()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
