"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.upsert_record_request_pipeline import UpsertRecordRequestPipeline
globals()['UpsertRecordRequestPipeline'] = UpsertRecordRequestPipeline
from sajari_client.model.upsert_record_request import UpsertRecordRequest


class TestUpsertRecordRequest(unittest.TestCase):
    """UpsertRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpsertRecordRequest(self):
        """Test UpsertRecordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpsertRecordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
