"""
    Search.io API

    Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import sajari_client
from sajari_client.api.promotions_api import PromotionsApi  # noqa: E501


class TestPromotionsApi(unittest.TestCase):
    """PromotionsApi unit test stubs"""

    def setUp(self):
        self.api = PromotionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_promotion(self):
        """Test case for create_promotion

        Create promotion  # noqa: E501
        """
        pass

    def test_delete_promotion(self):
        """Test case for delete_promotion

        Delete promotion  # noqa: E501
        """
        pass

    def test_get_promotion(self):
        """Test case for get_promotion

        Get promotion  # noqa: E501
        """
        pass

    def test_list_promotions(self):
        """Test case for list_promotions

        List promotions  # noqa: E501
        """
        pass

    def test_update_promotion(self):
        """Test case for update_promotion

        Update promotion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
