"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sajari_client
from sajari_client.model.batch_upsert_records_response_error import (
    BatchUpsertRecordsResponseError,
)
from sajari_client.model.batch_upsert_records_response_key import (
    BatchUpsertRecordsResponseKey,
)
from sajari_client.model.batch_upsert_records_response_variables import (
    BatchUpsertRecordsResponseVariables,
)

globals()["BatchUpsertRecordsResponseError"] = BatchUpsertRecordsResponseError
globals()["BatchUpsertRecordsResponseKey"] = BatchUpsertRecordsResponseKey
globals()["BatchUpsertRecordsResponseVariables"] = BatchUpsertRecordsResponseVariables
from sajari_client.model.batch_upsert_records_response import BatchUpsertRecordsResponse


class TestBatchUpsertRecordsResponse(unittest.TestCase):
    """BatchUpsertRecordsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchUpsertRecordsResponse(self):
        """Test BatchUpsertRecordsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BatchUpsertRecordsResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
