"""
    Sajari API

    Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@sajari.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import sajari_client
from sajari_client.api.schema_api import SchemaApi  # noqa: E501


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_create_schema_fields(self):
        """Test case for batch_create_schema_fields

        Batch create schema fields  # noqa: E501
        """
        pass

    def test_create_schema_field(self):
        """Test case for create_schema_field

        Create schema field  # noqa: E501
        """
        pass

    def test_list_schema_fields(self):
        """Test case for list_schema_fields

        List schema fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
