# flake8: noqa

"""
    Search.io API

    Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.  # noqa: E501

    The version of the OpenAPI document: v4
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from sajari_client.api_client import ApiClient

# import Configuration
from sajari_client.configuration import Configuration

# import exceptions
from sajari_client.exceptions import OpenApiException
from sajari_client.exceptions import ApiAttributeError
from sajari_client.exceptions import ApiTypeError
from sajari_client.exceptions import ApiValueError
from sajari_client.exceptions import ApiKeyError
from sajari_client.exceptions import ApiException
