# flake8: noqa

"""
    Search.io API

    The version of the OpenAPI document: 4.0.0
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from sajari_client.api_client import ApiClient

# import Configuration
from sajari_client.configuration import Configuration

# import exceptions
from sajari_client.exceptions import OpenApiException
from sajari_client.exceptions import ApiAttributeError
from sajari_client.exceptions import ApiTypeError
from sajari_client.exceptions import ApiValueError
from sajari_client.exceptions import ApiKeyError
from sajari_client.exceptions import ApiException
