"""
    Search.io API

    The version of the OpenAPI document: 4.0.0
    Contact: support@search.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from sajari_client.api_client import ApiClient, Endpoint as _Endpoint
from sajari_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from sajari_client.model.batch_create_schema_fields_request import BatchCreateSchemaFieldsRequest
from sajari_client.model.batch_create_schema_fields_response import BatchCreateSchemaFieldsResponse
from sajari_client.model.error import Error
from sajari_client.model.list_schema_fields_response import ListSchemaFieldsResponse
from sajari_client.model.schema_field import SchemaField


class SchemaApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.batch_create_schema_fields_endpoint = _Endpoint(
            settings={
                'response_type': (BatchCreateSchemaFieldsResponse,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/v4/collections/{collection_id}/schemaFields:batchCreate',
                'operation_id': 'batch_create_schema_fields',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'collection_id',
                    'batch_create_schema_fields_request',
                    'account_id',
                ],
                'required': [
                    'collection_id',
                    'batch_create_schema_fields_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'collection_id':
                        (str,),
                    'batch_create_schema_fields_request':
                        (BatchCreateSchemaFieldsRequest,),
                    'account_id':
                        (str,),
                },
                'attribute_map': {
                    'collection_id': 'collection_id',
                    'account_id': 'Account-Id',
                },
                'location_map': {
                    'collection_id': 'path',
                    'batch_create_schema_fields_request': 'body',
                    'account_id': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.create_schema_field_endpoint = _Endpoint(
            settings={
                'response_type': (SchemaField,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/v4/collections/{collection_id}/schemaFields',
                'operation_id': 'create_schema_field',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'collection_id',
                    'schema_field',
                    'parent',
                    'account_id',
                ],
                'required': [
                    'collection_id',
                    'schema_field',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'collection_id':
                        (str,),
                    'schema_field':
                        (SchemaField,),
                    'parent':
                        (str,),
                    'account_id':
                        (str,),
                },
                'attribute_map': {
                    'collection_id': 'collection_id',
                    'parent': 'parent',
                    'account_id': 'Account-Id',
                },
                'location_map': {
                    'collection_id': 'path',
                    'schema_field': 'body',
                    'parent': 'query',
                    'account_id': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.delete_schema_field_endpoint = _Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str, none_type,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/v4/collections/{collection_id}/schemaFields/{schema_field_name}',
                'operation_id': 'delete_schema_field',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'collection_id',
                    'schema_field_name',
                    'account_id',
                ],
                'required': [
                    'collection_id',
                    'schema_field_name',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'collection_id':
                        (str,),
                    'schema_field_name':
                        (str,),
                    'account_id':
                        (str,),
                },
                'attribute_map': {
                    'collection_id': 'collection_id',
                    'schema_field_name': 'schema_field_name',
                    'account_id': 'Account-Id',
                },
                'location_map': {
                    'collection_id': 'path',
                    'schema_field_name': 'path',
                    'account_id': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.list_schema_fields_endpoint = _Endpoint(
            settings={
                'response_type': (ListSchemaFieldsResponse,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/v4/collections/{collection_id}/schemaFields',
                'operation_id': 'list_schema_fields',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'collection_id',
                    'parent',
                    'account_id',
                    'page_size',
                    'page_token',
                ],
                'required': [
                    'collection_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'collection_id':
                        (str,),
                    'parent':
                        (str,),
                    'account_id':
                        (str,),
                    'page_size':
                        (int,),
                    'page_token':
                        (str,),
                },
                'attribute_map': {
                    'collection_id': 'collection_id',
                    'parent': 'parent',
                    'account_id': 'Account-Id',
                    'page_size': 'page_size',
                    'page_token': 'page_token',
                },
                'location_map': {
                    'collection_id': 'path',
                    'parent': 'query',
                    'account_id': 'header',
                    'page_size': 'query',
                    'page_token': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.update_schema_field_endpoint = _Endpoint(
            settings={
                'response_type': (SchemaField,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/v4/collections/{collection_id}/schemaFields/{schema_field_name}',
                'operation_id': 'update_schema_field',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'collection_id',
                    'schema_field_name',
                    'schema_field',
                    'account_id',
                    'update_mask',
                ],
                'required': [
                    'collection_id',
                    'schema_field_name',
                    'schema_field',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'collection_id':
                        (str,),
                    'schema_field_name':
                        (str,),
                    'schema_field':
                        (SchemaField,),
                    'account_id':
                        (str,),
                    'update_mask':
                        (str,),
                },
                'attribute_map': {
                    'collection_id': 'collection_id',
                    'schema_field_name': 'schema_field_name',
                    'account_id': 'Account-Id',
                    'update_mask': 'update_mask',
                },
                'location_map': {
                    'collection_id': 'path',
                    'schema_field_name': 'path',
                    'schema_field': 'body',
                    'account_id': 'header',
                    'update_mask': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def batch_create_schema_fields(
        self,
        collection_id,
        batch_create_schema_fields_request,
        **kwargs
    ):
        """Batch create schema fields  # noqa: E501

        The batch version of the [CreateSchemaField](/docs/api#operation/CreateSchemaField) call.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.batch_create_schema_fields(collection_id, batch_create_schema_fields_request, async_req=True)
        >>> result = thread.get()

        Args:
            collection_id (str): The collection to create the schema fields in, e.g. `my-collection`.
            batch_create_schema_fields_request (BatchCreateSchemaFieldsRequest):

        Keyword Args:
            account_id (str): The account that owns the collection, e.g. `1618535966441231024`.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            BatchCreateSchemaFieldsResponse
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['collection_id'] = \
            collection_id
        kwargs['batch_create_schema_fields_request'] = \
            batch_create_schema_fields_request
        return self.batch_create_schema_fields_endpoint.call_with_http_info(**kwargs)

    def create_schema_field(
        self,
        collection_id,
        schema_field,
        **kwargs
    ):
        """Create schema field  # noqa: E501

        Create a new field in a collection's schema.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_schema_field(collection_id, schema_field, async_req=True)
        >>> result = thread.get()

        Args:
            collection_id (str): The collection to create a schema field in, e.g. `my-collection`.
            schema_field (SchemaField): The schema field to create.

        Keyword Args:
            parent (str): The parent resource where the schema field is to be created.  Format:   - accounts/{account}/collections/{collection}   - accounts/{account}/collections/{collection}/schemaFields/{schemaField}. [optional]
            account_id (str): The account that owns the collection, e.g. `1618535966441231024`.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            SchemaField
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['collection_id'] = \
            collection_id
        kwargs['schema_field'] = \
            schema_field
        return self.create_schema_field_endpoint.call_with_http_info(**kwargs)

    def delete_schema_field(
        self,
        collection_id,
        schema_field_name,
        **kwargs
    ):
        """Delete schema field  # noqa: E501

        Deleting a schema field removes it from all records within the collection, however, references to the schema field in pipelines are not removed.  > Note: This operation cannot be reversed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_schema_field(collection_id, schema_field_name, async_req=True)
        >>> result = thread.get()

        Args:
            collection_id (str): The collection the schema field belongs to, e.g. `my-collection`.
            schema_field_name (str): The name of the schema field to delete.

        Keyword Args:
            account_id (str): The account that owns the collection, e.g. `1618535966441231024`.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            bool, date, datetime, dict, float, int, list, str, none_type
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['collection_id'] = \
            collection_id
        kwargs['schema_field_name'] = \
            schema_field_name
        return self.delete_schema_field_endpoint.call_with_http_info(**kwargs)

    def list_schema_fields(
        self,
        collection_id,
        **kwargs
    ):
        """List schema fields  # noqa: E501

        Retrieve a list of schema fields in a collection.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_schema_fields(collection_id, async_req=True)
        >>> result = thread.get()

        Args:
            collection_id (str): The collection that owns this set of schema fields, e.g. `my-collection`.

        Keyword Args:
            parent (str): The parent to list schema fields from.  Format:   - accounts/{account}/collections/{collection}   - accounts/{account}/collections/{collection}/schemaFields/{schemaField}. [optional]
            account_id (str): The account that owns the collection, e.g. `1618535966441231024`.. [optional]
            page_size (int): The maximum number of schema fields to return. The service may return fewer than this value.  If unspecified, at most 50 schema fields are returned.  The maximum value is 1000; values above 1000 are coerced to 1000.. [optional]
            page_token (str): A page token, received from a previous [ListSchemaFields](/docs/api#operation/ListSchemaFields) call.  Provide this to retrieve the subsequent page.  When paginating, all other parameters provided to [ListSchemaFields](/docs/api#operation/ListSchemaFields) must match the call that provided the page token.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ListSchemaFieldsResponse
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['collection_id'] = \
            collection_id
        return self.list_schema_fields_endpoint.call_with_http_info(**kwargs)

    def update_schema_field(
        self,
        collection_id,
        schema_field_name,
        schema_field,
        **kwargs
    ):
        """Update schema field  # noqa: E501

        Update the details of a schema field.  Only `name` and `description` can be updated.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_schema_field(collection_id, schema_field_name, schema_field, async_req=True)
        >>> result = thread.get()

        Args:
            collection_id (str): The collection the schema field belongs to, e.g. `my-collection`.
            schema_field_name (str): The name of the schema field to update.
            schema_field (SchemaField): The schema field details to update.

        Keyword Args:
            account_id (str): The account that owns the collection, e.g. `1618535966441231024`.. [optional]
            update_mask (str): The list of fields to update, separated by a comma, e.g. `name,description`.  Each field should be in snake case.  For each field that you want to update, provide a corresponding value in the schema field object containing the new value.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            SchemaField
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['collection_id'] = \
            collection_id
        kwargs['schema_field_name'] = \
            schema_field_name
        kwargs['schema_field'] = \
            schema_field
        return self.update_schema_field_endpoint.call_with_http_info(**kwargs)

